### ISSUE TITLE
Nothing is happening for me

### ISSUE THREAD

**Issue by favetelinguis** [zk/lt-gitstatusbar#1]
Just installed the plugin but nothing is showing up in the statusbar?

//H

**Comment by zk** [comment]
Two things to check:
1. There's a limitation in the plugin that requires you to restart LT before you'll see repo status, try restarting after plugin installation
2. Add the repo to your workspace directly, unfortunately status won't show if your repo is in a subdirectory in your workspace.

I've updated the readme to make this more clear (a5f2c756ef3890dc64dc9af53d7659c26d461379).

**Comment by favetelinguis** [comment]
Thanks that did the trick. One bad thing is how it updates, for example after i close the file and nothing is opened it still says master branch when it should just be the normal status bar.

**Comment by zk** [comment]
Strange, here's what happens on mine (0.8.3)

![ltgsb](https://cloud.githubusercontent.com/assets/7194/3077439/931e24c2-e42a-11e3-834a-f2ea2e5129cd.gif)

which seems like it's working correctly, are you seeing something different?

**Comment by favetelinguis** [comment]
Sorry it is me who am a retard. Everything is working fine now.

**Comment by zk** [comment]
No prob, thanks for the report :smiley:
